name: 'Setup OpenWPM env'
description: 'Sets up conda and installs dependencies'
runs:
  using: "composite"
  steps:
# All of these steps are just setup
    - name: Setting CONDA_PATH
      shell: bash
      run: echo "CONDA_PATH=$HOME/conda" >> $GITHUB_ENV
    - name: Setting OPENWPM_CONDA_PATH
      shell: bash
      run: echo "OPENWPM_CONDA_PATH=$CONDA_PATH/envs/openwpm" >> $GITHUB_ENV
    # If the environment.yaml hasn't changed we just reuse the entire conda install
    - id: cache
      uses: actions/cache@v4
      env:
        cache-name: conda-cache
      with:
        path: ${{ env.CONDA_PATH }}
        key: ${{ env.cache-name }}-${{ hashFiles('environment.yaml') }}

    - name: Install conda
      shell: bash
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: $GITHUB_WORKSPACE/scripts/install-conda.sh

    - shell: bash
      run: echo "$CONDA_PATH/bin" >> $GITHUB_PATH

    - name: Install.sh (cache miss)
      shell: bash
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      run: $GITHUB_WORKSPACE/install.sh
    - name: Install.sh (cache hit)
      shell: bash
      if: ${{ steps.cache.outputs.cache-hit == 'true' }}
      run: $GITHUB_WORKSPACE/install.sh --skip-create
    - shell: bash
      run: echo "$OPENWPM_CONDA_PATH/bin" >> $GITHUB_PATH
    # Now we have a working OpenWPM environment
