[tool.pytest.ini_options]
python_files="test_*.py"
testpaths="test"
addopts = "--strict-markers"

markers = [
    "pyonly: marks a test as being python only and so server and xpi not needed",
    "slow: marks a test as slow (omit slow tests with '-m \"not slow\"')"
]

[tool.isort]
profile = "black"
known_future_library = "future"
known_first_party = ["openwpm","openwpmtest","test"]
default_section = "THIRDPARTY"
skip = ["venv","Extension","firefox-bin"]
