/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The JS object to be instrumented.
 */
export type JSObject = string;
/**
 * The name recorded by the instrumentation for this object.
 */
export type InstrumentedName = string;
/**
 * An array of properties to instrument on this object. If array is empty, then all properties are instrumented.
 */
export type PropertiesToInstrument =
  | (
      | {
          depth: number;
          propertyNames: string[];
        }
      | string
    )[]
  | null;
/**
 * An array of non-existing properties to instrument on this object.
 */
export type NonExistingPropertiesToInstrument = string[];
/**
 * Properties excluded from instrumentation.
 */
export type ExcludedProperties = string[];
/**
 * Set to true save the call stack info with each property call.
 */
export type LogCallStack = boolean;
/**
 * Set to true to save args that are functions as strings during argument serialization. If false `FUNCTION` is recorded.
 */
export type LogFunctionsAsStrings = boolean;
/**
 * Set true to log get requests to properties that are functions. If true when a call is made, the log will contain both the call and a get log.
 */
export type LogFunctionGets = boolean;
/**
 * Set to true to prevent nested objects and functions from being overwritten (and thus having their instrumentation removed). Other properties (static values) can still be set with this is enabled.
 */
export type PreventSets = boolean;
/**
 * Set to `true` to recursively instrument all object properties of the given `object`. NOTE: (1) `propertiesToInstrument` does not propagate to sub-objects. (2) Sub-objects of prototypes can not be instrumented recursively as these properties can not be accessed until an instance of the prototype is created.
 */
export type Recursive = boolean;
/**
 * Stealth-only. For a SHARED-PROTOTYPE (inherited) method hooked once on a real-interface prototype (e.g. `addEventListener` on `EventTarget.prototype`): the set of concrete receiver interface names whose calls should be recorded. At call time the privileged forwarder reads the receiver's interface name (its `constructor.name`, read through the Xray so page tampering cannot fool it); a call is EMITTED only when that name is in this set. The recorded `symbol` stays the STATIC shared-prototype method `<owner>.<method>` (e.g. `EventTarget.addEventListener`); the concrete receiver interface is written to the dedicated `receiver` column, not encoded into `symbol`. Attribution is interface-level, not instance-level, by design. When absent, the method is instrumented with a static symbol, the `receiver` column is null, and every call is recorded (unchanged behaviour).
 */
export type ReceiverInterfacesOfInterest = string[];
/**
 * Recursion limit when instrumenting object recursively
 */
export type RecursionDepth = number;
/**
 * A property whose value will be overwritten during instrumentation
 */
export type OverwrittenProperty =
  | {
      /**
       * The property that will be overwritten
       */
      key: string;
      /**
       * The value that should be returned
       */
      value:
        | string
        | unknown[]
        | {
            [k: string]: unknown;
          }
        | boolean
        | number
        | number;
      level: PrototypeLevel;
      [k: string]: unknown;
    }[]
  | null;
/**
 * The depth in the prototype chain where the property resides
 */
export type PrototypeLevel = number;
/**
 * Schema describing the JSON to be passed to JS Instrument Settings.
 */
export type JSInstrumentSettings = SettingsObjects[];

export interface SettingsObjects {
  object: JSObject;
  instrumentedName: InstrumentedName;
  depth?: number;
  logSettings: LogSettings;
}
/**
 * The log settings object.
 */
export interface LogSettings {
  propertiesToInstrument: PropertiesToInstrument;
  nonExistingPropertiesToInstrument: NonExistingPropertiesToInstrument;
  excludedProperties: ExcludedProperties;
  logCallStack: LogCallStack;
  logFunctionsAsStrings: LogFunctionsAsStrings;
  logFunctionGets: LogFunctionGets;
  preventSets: PreventSets;
  recursive: Recursive;
  receiverInterfaces?: ReceiverInterfacesOfInterest;
  depth: RecursionDepth;
  overwrittenProperties?: OverwrittenProperty;
}
