export const jsInstrumentationSettings = [
  {"object":"ScriptProcessorNode",// Depcrecated. Replaced by AudioWorkletNode
  "instrumentedName":"ScriptProcessorNode",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"AudioWorkletNode",
  "instrumentedName":"AudioWorkletNode",
  "depth":1,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"GainNode",
  "instrumentedName":"GainNode",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"AnalyserNode",
  "instrumentedName":"AnalyserNode",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"OscillatorNode",
  "instrumentedName":"OscillatorNode",
  "depth":1,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  // Add shared prototype by AnalyserNode, OscillatorNode, ScriptProcessorNode, GainNode, ScriptProcessorNode
  {"object":"AnalyserNode",
  "instrumentedName":"Node",
  "depth":1,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"OfflineAudioContext",
  "instrumentedName":"OfflineAudioContext",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"AudioContext",
  "instrumentedName":"AudioContext",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

// Add shared prototype by AudioContenxt/OfflineAudioContext
  {"object":"AudioContext",
  "instrumentedName":"[AudioContenxt|OfflineAudioContext]",
  "depth":1,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"RTCPeerConnection",
  "instrumentedName":"RTCPeerConnection",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"HTMLCanvasElement",
  "instrumentedName":"HTMLCanvasElement",
  "depth":1,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":["style", "offsetWidth", "offsetHeight"],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"Storage",
  "instrumentedName":"Storage",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"Navigator",
  "instrumentedName":"Navigator",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[{"key":"webdriver", "value":false, "level":0}],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"CanvasRenderingContext2D",
  "instrumentedName":"CanvasRenderingContext2D",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[
    "transform",
    "globalAlpha",
    "clearRect",
    "closePath",
    "canvas",
    "quadraticCurveTo",
    "lineTo",
    "moveTo",
    "setTransform",
    "drawImage",
    "beginPath",
    "translate"],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"Screen",
  "instrumentedName":"Screen",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[],
  // in OpenWPM is only this one used:
  //{"depth":0, "propertyNames":["colorDepth","pixelDepth"
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":false,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

  {"object":"document",
  "instrumentedName":"document",
  "depth":0,
  "logSettings":{"propertiesToInstrument":[{"depth":2, "propertyNames":["referrer"]}],
  "nonExistingPropertiesToInstrument":[],
  "excludedProperties":[],
  "overwrittenProperties":[],
  "logCallStack":true,
  "logFunctionsAsStrings":false,
  "logFunctionGets":false,
  "preventSets":false,
  "recursive":false,
  "depth":5}},

];