channels:
- conda-forge
- main
dependencies:
- beautifulsoup4=4.9.3
- black=21.5b2
- click=8.0.1
- codecov=2.1.11
- dill=0.3.3
- gcsfs=2021.5.0
- geckodriver=0.26.0
- ipython=7.24.1
- leveldb=1.23
- multiprocess=0.70.11.1
- mypy=0.812
- nodejs=14.15.4
- pandas=1.2.4
- pillow=8.2.0
- pip=21.1.2
- pre-commit=2.13.0
- psutil=5.8.0
- pyarrow=4.0.1
- pytest-asyncio=0.15.1
- pytest-cov=2.12.1
- pytest=6.2.4
- python=3.9.4
- pyvirtualdisplay=2.1
- recommonmark=0.7.1
- redis-py=3.5.3
- s3fs=2021.5.0
- selenium=3.141.0
- sentry-sdk=1.1.0
- sphinx-markdown-tables=0.0.15
- sphinx=4.0.2
- tabulate=0.8.9
- tblib=1.7.0
- wget=1.20.1
- pip:
  - dataclasses-json==0.5.4
  - domain-utils==0.7.1
  - jsonschema==3.2.0
  - plyvel==1.3.0
name: openwpm
